Create/edit movie form
Daniel-Vasquez/rest-api-react pull request #1
Opened 2023-08-27 05:54 UTC by Daniel-Vasquez

Change of design and logic of the Create and Edit form, for better navigation.

2023-08-29 04:59 UTC, AngelVasquezNep requested changes

2023-08-29 04:59 UTC, AngelVasquezNep commented on src/App.jsx
> +    await fetch('https://rest-api-ytw2-dev.fl0.io/movies')
Este tipo de datos siempre es mejor que llegue por variable de entorno

2023-08-29 04:59 UTC, AngelVasquezNep commented on src/App.jsx
> +    await createMovie(title, newPoster, year, director, duration, rate, genre.split(','));
createMovie podría recibir más bien un objeto, así si mañana quieres agregar o quitar un nuevo valor, será más fácil
```js
createMoview({ title, newPoster... })
```

2023-08-29 04:59 UTC, AngelVasquezNep commented on src/App.jsx
>      setGenre('');
Una forma sencilla (aunque no es la mejor) de manejar esto sería tener un sólo `useState`:

```js
const [editedMovie, setEditedMovie] = useState({
   title: '',
   year: '',
   ... etc
})

function handleChangeInput(event) {
   setEditedMovie((currentValues) => {
      ...currentValues, //Acá copias los valores actuales
      [event.target.name]: event.target.value, // Acá actualizas sólo el input que cambió
  })
}


<input
     name="title" // De acá sale  `target.name`
    onChange={handleChangeInput}
/>
```

2023-08-29 04:59 UTC, AngelVasquezNep commented on src/App.jsx
> +  if (isLoaded) return <Loading />
```js
  if (isLoaded) {
       return <Loading />
  }
```

2023-08-29 04:59 UTC, AngelVasquezNep commented on src/App.jsx
> +            `container-button__button ${showForm ? 'button-color' : ''}`
Intente mirar la biblioteca `classnames` https://www.npmjs.com/package/classnames
Me gusta y ayuda con estas clases dinámicas

2023-08-29 04:59 UTC, AngelVasquezNep commented on src/App.jsx
> +            handleSubmit={handleSubmit}
Si cambias el useState arriba, acá podrías sólo pasar algo como `movie={movie}`

2023-08-29 04:59 UTC, AngelVasquezNep commented on src/App.jsx
> +                title: title ? title : '',
```js
title: title || ''
year: year || ''
genre: genre || 'Action'
...
```

2023-08-29 04:59 UTC, AngelVasquezNep commented on src/components/Form.jsx
> +  }
Este patrón es un poco extraño, por un lado `useState` es el nombre de un hook, quizá querías ayudaría llamarle `setState`
También es extraño que si ya recibe el valor y el setter (la función que setea el valor), quizá directamente podrías llamar la función dentro del onChange de cada input.
Creo que con el cambio del hook del form ya no será necesario esto pero igual quería comentarlo 😄

2023-08-29 04:59 UTC, AngelVasquezNep commented on src/components/Form.jsx
> +          value={duration ? duration : ""}
value={duration || ""}

2023-08-29 04:59 UTC, AngelVasquezNep commented on src/components/Form.jsx
> +          defaultValue={Array.isArray(genre) ? genre[0] : genre}
¿Porqué `genre` a veces puede ser un array?

2023-08-29 04:59 UTC, AngelVasquezNep commented on src/components/Modal.jsx
> +              <option value="Action">Action</option>
Este componente se repite, podría ser un componente solito

2023-08-29 04:59 UTC, AngelVasquezNep commented on src/App.css
> +.container-title-no-movies {
Los estilos dentro de `App.css` son globales, creo que podrías explotar la opción de tener todos estos estilos en sus archivos `.module.css`

2023-09-05 04:51 UTC, Daniel-Vasquez commented
@AngelVasquezNep 
He completado las modificaciones sugeridas en mi código, gracias.

2023-09-12 03:39 UTC, AngelVasquezNep approved these changes

2023-09-12 03:39 UTC, AngelVasquezNep commented on .env
> +VITE_ENDPOINT=https://rest-api-ytw2-dev.fl0.io
Crear `.gitignore`, casi siempre uso este: https://github.com/github/gitignore/blob/main/Node.gitignore

2023-09-12 03:39 UTC, AngelVasquezNep commented on src/App.jsx
> +  const [movieData, setMovieData] = useState({
Este objeto se usa abajo, en `setMovieData({...`, así que podría esstar por fuera de App y sólo usarlo

Tipo:

```js
const EMPTY_MOVIE = {
    title: '',
    year: '',
    director: '',
    duration: '',
    rate: '',
    genre: 'Action'
}
```

2023-09-12 03:39 UTC, AngelVasquezNep commented on src/App.jsx
> +        {movies.length === 0 && <h1 className={styleContainer["container-title-no-movies"]}>No movies</h1>}
Usar prettier

2023-09-12 03:39 UTC, AngelVasquezNep commented on src/components/FormMovie/index.jsx
> +          value={year ? year : ""}
year || ""

2023-09-12 03:39 UTC, AngelVasquezNep commented on src/components/FormMovie/index.jsx
> +          value={duration ? duration : ""}
duration || ""

2023-09-12 03:39 UTC, AngelVasquezNep commented on src/components/ModalDelete/index.module.css
> +  background-color: #000000be;
¿Esto existe?

2023-09-12 03:39 UTC, AngelVasquezNep commented on src/components/OptionsButtons/index.jsx
> +    action(movies, setMovies, setIsLoading);
Mejorar, intentar no pasar los `setSomething` como param

2023-09-12 03:39 UTC, AngelVasquezNep commented on src/components/OptionsButtons/index.module.css
> +  transition: all .14s ease-out;
0.14s

2023-09-12 04:59 UTC, merged